Fix prop rename
PolymerElements/iron-resizable-behavior pull request #44
Opened 2018-06-25 23:21 UTC by e111077

Listen and unlisten cause issues with property renaming.

2018-06-25 23:59 UTC, bicknellr requested changes
Could you mention why these changes are being made in the method comments?

2018-06-25 23:59 UTC, bicknellr commented on iron-resizable-behavior.html
> +    subscribeIronResize: function(target) {
Like you mentioned offline, I think you should prefix these with `_` .

2018-06-26 00:21 UTC, e111077 commented
comments added

2018-06-26 00:30 UTC, merged

2018-06-26 00:30 UTC, bicknellr commented
Thanks!